/**
 * Tiny Handlebars-style renderer (subset: {{var}} and {{nested.path}}).
 * Avoids pulling in the full handlebars dep until puppeteer is wired; the same
 * template syntax stays compatible with handlebars when we swap.
 */
export function renderTemplate(template: string, ctx: Record<string, unknown>): string {
  return template.replace(/\{\{\s*([\w.]+)\s*\}\}/g, (_, path: string) => {
    const value = path
      .split('.')
      .reduce<unknown>(
        (acc, key) =>
          acc != null && typeof acc === 'object' && key in (acc as Record<string, unknown>)
            ? (acc as Record<string, unknown>)[key]
            : undefined,
        ctx,
      );
    if (value == null) return '';
    if (typeof value === 'object') return JSON.stringify(value);
    return String(value);
  });
}

export function buildOfferHtml(args: {
  bodyHtml: string;
  branding?: { logoUrl?: string; primaryColor?: string; fontFamily?: string };
  candidateName: string;
  orgName: string;
}) {
  const primary = args.branding?.primaryColor || '#0f172a';
  const font = args.branding?.fontFamily || 'Inter, system-ui, sans-serif';
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>Offer Letter — ${escapeHtml(args.candidateName)}</title>
<style>
  body { font-family: ${font}; color: #0f172a; padding: 48px 56px; line-height: 1.6; max-width: 760px; margin: 0 auto; }
  header { display: flex; align-items: center; justify-content: space-between; border-bottom: 2px solid ${primary}; padding-bottom: 16px; margin-bottom: 32px; }
  header img { max-height: 48px; }
  h1 { color: ${primary}; font-size: 22px; }
  .meta { font-size: 13px; color: #64748b; }
  footer { margin-top: 48px; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 12px; }
  .body { font-size: 14px; }
  .body p { margin: 12px 0; }
</style>
</head>
<body>
  <header>
    <div>
      <h1>${escapeHtml(args.orgName)}</h1>
      <div class="meta">Offer of Employment</div>
    </div>
    ${args.branding?.logoUrl ? `<img src="${escapeAttr(args.branding.logoUrl)}" alt="${escapeAttr(args.orgName)}" />` : ''}
  </header>
  <div class="body">${args.bodyHtml}</div>
  <footer>Generated by ${escapeHtml(args.orgName)} via Work Nucleus</footer>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function escapeAttr(s: string): string {
  return escapeHtml(s);
}
